# This workflow will install Python dependencies, run tox

name: tox-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python: [3.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Update Pip, then install Poetry and Tox
        run: |
          python -m pip install --upgrade pip
          pip install poetry tox
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: |
          tox -e py
